# Introducción a Numpy
Numpy es una librería fundamental para la computación cientifica con Python.
* Proporciona arrays N-dimensionales.
* Implementa funciones matemáticas sofisticadas.
* Proporciona mecanismos para facilitar generar números aleatorios.

In [ ]:
# Importar librería
import numpy as np

## Arrays 
Un array es una estructura de datos que consiste en una colección de elementos, identificado por al menos un índice. (Array Unidemensional, Array multidimensional)

### Arrays Caracteristicas
* Cada dimensión se denomina <b>axis</b>
* El número de dimensiones se denomina <b>rank</b>
* La lista de dimensiones con su correspondiente longitud se denomina <b>shape</b>
* El número total de elementos del array se denomina <b>size</b>

In [ ]:
# 2 Filas, 4 Columnas con 0 en cada una de las posiciones
array = np.zeros((2, 4)) 

In [ ]:
array

In [ ]:
array.shape # (2,4) -> (longitud fila, longitud columna)

In [ ]:
array.ndim # Rank o dimensiones del arreglo

In [ ]:
array.size # Tamaño array, o cantidad de todos los elementos

## Creación de Arrays

In [ ]:
# Array cuyos valores son todos 0
np.zeros( (2,3,4) ) 

In [ ]:
# Array cuyos valores son todos 1
np.ones( (2,3,4) )

In [ ]:
# Array cuyos valores son todos el valor indicado como segundo parámetro de la función
# np.full( SHAPE, VALOR )
np.full( (2,3,4), 29)

In [ ]:
# Array cuyos valores son todos los valores en memoria en donde se inicializo ese espacio del array
np.empty( (2,3,3) )

In [ ]:
# Inicialización del array utilizando un array de Python
arreglo_python = [ [1,2,3], [4,5,6] ]
arreglo_numpy = np.array( arreglo_python )
arreglo_numpy
arreglo_numpy.shape

## Creación de Arrays avanzado

In [ ]:
# Creación del array utilizando una función basada en rangos
# No son aleatorios en rango si no distribuidos entre el minimo y maximo
# (minimo, maximo, número de elementos)
arreglo = np.linspace(0,7,10) # Rango entre 0 y 6, 10 elementos
arreglo.shape
arreglo

In [ ]:
# Inicialización del array con valores aleatorios
np.random.rand(2,5)

In [ ]:
# Inicialización del Array utilizando una función personalizada
def func(x, y):
  # x = primer índice en el arreglo
  # y = segundo índice en el arreglo
  return x + y

np.fromfunction(func, (3,5))

### Acceso a los elementos de un array

#### Array unidimensional

In [20]:
array_uni = np.array([1,3,5,7,9,11])
print("Shape:", array_uni.shape)
print("Array_uni:", array_uni)
print(type(array_uni))

Shape: (6,)
Array_uni: [ 1  3  5  7  9 11]
<class 'numpy.ndarray'>


In [21]:
# Accediendo al quinto elemento del Array
array_uni[4]

9

In [19]:
# Accediendo al tercer y cuarto elemento del Array
array_uni[2:4]

array([5, 7])

In [22]:
# Accediendo a los elementos con diferente step
array_uni[0::2]

array([1, 5, 9])

#### Array multidimensional

In [23]:
# Creación array multidimension
array_multi = np.array([[1,2,3,4], [5,6,7,8]])
print("Shape:", array_multi.shape)
print("Array_uni:", array_multi)

Shape: (2, 4)
Array_uni: [[1 2 3 4]
 [5 6 7 8]]


In [25]:
# Accediendo al cuarto elemento
array_multi[0,3]

4

In [24]:
# Accediendo a una fila
array_multi[1,:]

array([5, 6, 7, 8])

In [26]:
# Accediendo al tercer elemento de las dos primera filas del Array
array_multi[0:2, 2]

array([3, 7])

In [27]:
# Accediendo a columna 4
array_multi[:,3]

array([4, 8])

### Modificación de un Array

In [30]:
# Creación de un Array unidimensional.
array1 = np.arange(28) # Array con elementos de 0-27
print("Shape:", array1.shape)
print("Array_uni:", array1)

Shape: (28,)
Array_uni: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [33]:
# Cambiar las dimensiones del Array y sus longitudes
array1.shape = (7,2,2) # 7x2x2 = 28 elementos
array1.shape = (7,4) # 7x4 = 28 elementos
print("Shape:", array1.shape)
print("Array_uni:", array1)

Shape: (7, 4)
Array_uni: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [ ]:
# Crear copia con el reshape y cambiarle el shape
array2 = array1.copy().reshape(4,7)
array2

In [ ]:
# Modificación del nuevo Array devuelto
array2[0,3] = 20
array2

In [34]:
# Desenvolver el array volviendo a solo una dimension
array_ravel = array1.copy().ravel()
array_ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

### Operaciones aritméticas con Arrays

In [35]:
# Creación de Arrays unidimensioneales
array1 = np.arange(2,18,2) # start, stop, step
array2 = np.arange(8)
print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [ 2  4  6  8 10 12 14 16]
Array 2: [0 1 2 3 4 5 6 7]


In [36]:
# Suma
array1 + array2

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [37]:
# Resta
array1 - array2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# Multiplicación
# Importante: No es una multiplicación de matrices
array1 * array2

array([  0,   4,  12,  24,  40,  60,  84, 112])

#### Broadcasting
Si se aplican operaciones aritmeticas sobre Arrays que no tienen la misma forma (shape) Numpy aplica una propiedad que se denomina Broadcasting.

In [39]:
# Creación de dos Arrays unidimensionales
array1 = np.arange(5)
array2 = np.array([3])
print("Shape Array 1:", array1.shape)
print("Array 1:", array1)
print()
print("Shape Array 2:", array2.shape)
print("Array 2:", array2)

Shape Array 1: (5,)
Array 1: [0 1 2 3 4]

Shape Array 2: (1,)
Array 2: [3]


In [40]:
# Suma de ambos Arrays
array1 + array2

array([3, 4, 5, 6, 7])

### Funciones estadísticas sobre Arrays

In [ ]:
# Creación de un Array unidimensional
array1 = np.arange(1,20,2)
print(array1)

In [ ]:
# Media de los elementos del Array
array1.mean()

In [ ]:
# Suma de los elementos del Array
array1.sum()

In [ ]:
# Cuadrado de los elementos del Array
np.square(array1)

In [ ]:
# Raiz cuadrada de los elementos del Array
np.sqrt(array1)

In [ ]:
# Exponencial de los elementos del array
np.exp(array1)

In [ ]:
# Logaritmo de los elementos del Array
np.log(array1)