# Introducción a Numpy
Numpy es una librería fundamental para la computación cientifica con Python.
* Proporciona arrays N-dimensionales.
* Implementa funciones matemáticas sofisticadas.
* Proporciona mecanismos para facilitar generar números aleatorios.

In [2]:
# Importar librería
import numpy as np

## Arrays 
Un array es una estructura de datos que consiste en una colección de elementos, identificado por al menos un índice. (Array Unidemensional, Array multidimensional)

### Arrays Caracteristicas
* Cada dimensión se denomina <b>axis</b>
* El número de dimensiones se denomina <b>rank</b>
* La lista de dimensiones con su correspondiente longitud se denomina <b>shape</b>
* El número total de elementos del array se denomina <b>size</b>

In [ ]:
array = np.zeros( (2,4) )  # 2 Filas, 4 Columnas con 0 en cada una de las posiciones

In [ ]:
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array.shape # (2,4) -> (longitud fila, longitud columna)

(2, 4)

In [ ]:
array.ndim # Rank o dimensiones del arreglo

2

In [ ]:
array.size # Tamaño array, o cantidad de todos los elementos

8

## Creación de Arrays

In [ ]:
# Array cuyos valores son todos 0
np.zeros( (2,3,4) ) 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# Array cuyos valores son todos 1
np.ones( (2,3,4) )

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# Array cuyos valores son todos el valor indicado como segundo parámetro de la función
# np.full( SHAPE, VALOR )
np.full( (2,3,4), 29)

array([[[29, 29, 29, 29],
        [29, 29, 29, 29],
        [29, 29, 29, 29]],

       [[29, 29, 29, 29],
        [29, 29, 29, 29],
        [29, 29, 29, 29]]])

In [ ]:
# Array cuyos valores son todos los valores en memoria en donde se inicializo ese espacio del array
np.empty( (2,3) )

array([[1.8517857e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [ ]:
# Inicialización del array utilizando un array de Python
arreglo_python = [ [1,2,3], [4,5,6] ]
arreglo_numpy = np.array( arreglo_python )
arreglo_numpy
arreglo_numpy.shape

(2, 3)

## Creación de Arrays avanzado

In [ ]:
# Creación del array utilizando una función basada en rangos
# No son aleatorios en rango si no distribuidos entre el minimo y maximo
# (minimo, maximo, número de elementos)
arreglo = np.linspace(0,7,10) # Rango entre 0 y 6, 10 elementos
arreglo.shape
arreglo

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [ ]:
# Inicialización del array con valores aleatorios
np.random.rand(2,5)

array([[0.89042913, 0.53995336, 0.62024695, 0.3506826 , 0.07385543],
       [0.7943934 , 0.29234609, 0.49857219, 0.45018202, 0.74638832]])

In [ ]:
# Inicialización del Array utilizando una función personalizada
def func(x, y):
  # x = primer índice en el arreglo
  # y = segundo índice en el arreglo
  return x + y

np.fromfunction(func, (3,5))

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.]])

### Acceso a los elementos de un array

#### Array unidimensional

In [4]:
array_uni = np.array([1,3,5,7,9,11])
print("Shape:", array_uni.shape)
print("Array_uni:", array_uni)

Shape: (6,)
Array_uni: [ 1  3  5  7  9 11]


In [5]:
# Accediendo al quinto elemento del Array
array_uni[4]

9

In [6]:
# Accediendo al tercer y cuarto elemento del Array
array_uni[2:4]

array([5, 7])

In [7]:
# Accediendo a los elementos con diferente step
array_uni[0::2]

array([1, 5, 9])

#### Array multidimensional

In [8]:
# Creación array multidimension
array_multi = np.array([[1,2,3,4], [5,6,7,8]])
print("Shape:", array_multi.shape)
print("Array_uni:", array_multi)

Shape: (2, 4)
Array_uni: [[1 2 3 4]
 [5 6 7 8]]


In [9]:
# Accediendo al cuarto elemento
array_multi[0,3]

4

In [10]:
# Accediendo a una fila
array_multi[1,:]

array([5, 6, 7, 8])

In [11]:
# Accediendo al tercer elemento de las dos primera filas del Array
array_multi[0:2, 2]

array([3, 7])

In [15]:
# Accediendo a columna 4
array_multi[:,3]

array([4, 8])

### Modificación de un Array

In [16]:
# Creación de un Array unidimensional.
array1 = np.arange(28) # Array con elementos de 0-27
print("Shape:", array1.shape)
print("Array_uni:", array1)

Shape: (28,)
Array_uni: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [17]:
# Cambiar las dimensiones del Array y sus longitudes
array1.shape = (7,4)
print("Shape:", array1.shape)
print("Array_uni:", array1)

Shape: (7, 4)
Array_uni: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [20]:
# Crear copia con el reshape y cambiarle el shape
array2 = array1.copy().reshape(4,7)
array2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [22]:
# Modificación del nuevo Array devuelto
array2[0,3] = 20
array2

array([[ 0,  1,  2, 20,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [23]:
# Desenvolver el array volviendo a solo una dimension
array_ravel = array1.copy().ravel()
array_ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

### Operaciones aritméticas con Arrays

In [24]:
# Creación de Arrays unidimensioneales
array1 = np.arange(2,18,2) # start, stop, step
array2 = np.arange(8)
print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [ 2  4  6  8 10 12 14 16]
Array 2: [0 1 2 3 4 5 6 7]


In [25]:
# Suma
array1 + array2

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [26]:
# Resta
array1 - array2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# Multiplicación
# Importante: No es una multiplicación de matrices
array1 * array2

array([  0,   4,  12,  24,  40,  60,  84, 112])

#### Broadcasting
Si se aplican operaciones aritmeticas sobre Arrays que no tienen la misma forma (shape) Numpy aplica una propiedad que se denomina Broadcasting.

In [29]:
# Creación de dos Arrays unidimensionales
array1 = np.arange(5)
array2 = np.array([3])
print("Shape Array 1:", array1.shape)
print("Array 1:", array1)
print()
print("Shape Array 2:", array2.shape)
print("Array 2:", array2)

Shape Array 1: (5,)
Array 1: [0 1 2 3 4]

Shape Array 2: (1,)
Array 2: [3]


In [31]:
# Suma de ambos Arrays
array1 + array2

array([3, 4, 5, 6, 7])

### Funciones estadísticas sobre Arrays

In [32]:
# Creación de un Array unidimensional
array1 = np.arange(1,20,2)
print(array1)

[ 1  3  5  7  9 11 13 15 17 19]


In [33]:
# Media de los elementos del Array
array1.mean()

10.0

In [34]:
# Suma de los elementos del Array
array1.sum()

100

In [35]:
# Cuadrado de los elementos del Array
np.square(array1)

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [36]:
# Raiz cuadrada de los elementos del Array
np.sqrt(array1)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])

In [37]:
# Exponencial de los elementos del array
np.exp(array1)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08])

In [38]:
# Logaritmo de los elementos del Array
np.log(array1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])